---
#####
# https://github.com/probot/settings/blob/master/README.md
_extends: "cloud"
repository:
  name: "proto"
  topics: ["protobuf", "kubelt"]
  description: "API definitions for kubelt systems using OpenAPIv3 specifications to generate to protobufs and finally Go."
  allow_merge_commits: false
  allow_rebase_merge: false
  allow_squash_merge: true
  archived: false
  auto_init: false
  delete_branch_on_merge: true
  has_downloads: false
  has_issues: true
  has_wiki: false
  is_template: false
  visibility: "public"
  vulnerability_alerts: true

branches:
  - name: master
    protection:
      enforce_admins: true
      required_signed_commits: false
      required_pull_request_reviews:
        required_approving_reviews_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      required_status_checks:
        strict: true
        contexts: []
      restrictions:
        apps: []
        users: []
        teams: []

labels:
  - name: bug
    color: CC0000
    description: An issue with the system 🐛.

  - name: feature
    color: '#336699'
    description: New functionality.

  - name: first-timers-only

milestones:
  - title: alpha
    state: open
