openapi: 3.0.0
info:
  version: v1alpha1
  title: kubelt RPC
  license:
    name: Apache 3.0
paths:
  /apply:
    post:
      summary: Apply kubelt resources
      operationId: apply
      parameters:
        - in: body
          name: Context
          schema:
            $ref: '#/components/schemas/Context'
        - in: body
          name: Resources
          schema:
            $ref: '#/components/schemas/Cue'
      responses:
        '201':
          description: Null created response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  resources:
                    $ref: '#/components/schemas/CueList'
                  error:
                    $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    CloudEvent:
      type: object
      description: cloud event
      properties:
        specversion:
          description: |
            [required] The version of the CloudEvents specification which this
            event uses. MUST use a value of "1.0" for the current version of
            the specification.
          type: string
        id:
          description: |
            [required] Identifies the event. Producers MUST ensure that
            "source" + "id" is unique for each distinct event. If a duplicate
            event is sent (due to e.g. network transmission error) it MAY
            reuse the same "id".
          type: string
        source:
          description: |
            [required] Identifies the context in which an event
            happened. Often this includes information such as the type of the
            event source, organization publishing the event, or process that
            produced the event. Exact syntax and semantics are defined by the
            event producer.

            Producer MUST ensure that "source" + "id" is unique for each
            distinct event.

            An application MAY assign a unique "source" to each distinct
            producer, making it easy to produce unique IDs as no other
            producer will have the same source. Application MAY use UUIDs,
            URNs, DNS authorities or an application-specific scheme to create
            unique "source" identifiers.

            An absolute URI is RECOMMENDED.
          type: URI
        type:
          description: |
            [required] A value describing the type of event related to the
            originating occurrence. Format is producer defined and might
            include information such as the version of the "type".

            SHOULD be prefixed with a reverse-DNS name indicating the
            organization which defines the semantics of this event type.
          type: string
        datacontenttype:
          description: |
            [optional] FIXME
          type: MediaType
        dataschema:
          description: |
            [optional] FIXME
          type: URI
        subject:
          description: |
            [optional] The subject of the event in the context of the event
            producer.
          type: string
        time:
          description: |
            [optional] Timestamp of when the occurrence happened. If present,
            MUST adhere to time format specified in RFC 3339. NB: gRPC
            "timestamp" time adheres to this requirement.
          type: date-time
          format: RFC3339
    Context:
      type: object
      description: |
        The context to execute the command against.
      properties:
        name:
          description: |
            [required] The name of the context a command is inteded to run against.
            Producers must ensure this name is available in the ktrl.cue config.
          type: string
    Cue:
      type: object
      description: |
        A cue file represented as a string.
      properties:
        cue:
          type: string
          description: |
            [required] A cue file represetned as a string. This string must be valid cue
            and will be validated by the reciever.
    CueList:
      type: object
      description: |
        A list of cue structs represented as a string.
      properties:
        cue:
          type: array
          description: |
            [required] A list of cue structs represented as a string. The reciever should
            compile these string into cue.Value for evaluation and validation.
          items:
            type: string
    MediaType:
      type: object
      description: internet media type
      properties:
        type:
          description: FIXME
          type: string
        subtype:
          description: FIXME
          type: string
        suffix:
          description: FIXME
          type: string
        parameters:
          description: FIXME
          type: string
    URI:
      type: object
      description: universal resource indicator
      properties:
        name:
          description: FIXME
          type: string
