# TODO: breakdown further following this pattern
# https://davidgarcia.dev/posts/how-to-split-open-api-spec-into-multiple-files/
openapi: "3.0.0"
info:
  version: v1alpha1
  title: kubelt RPC
  license:
    name: Apache 3.0

paths:
  /apply:
    post:
      summary: Apply kubelt resources
      operationId: apply
      parameters:
        - in: body
          name: Context
          schema:
            $ref: './schemas/_index.yaml#/Context'
        - in: body
          name: Resources
          schema:
            $ref: './schemas/_index.yaml#/Cue'
      responses:
        "201":
          description: Null created response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  resources:
                    $ref: './schemas/_index.yaml#/CueList'
                  error:
                    $ref: '#/components/schemas/Error'

components:
  schemas:
    $ref: './schemas/_index.yaml'
    Error:
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
